# -*- coding: utf-8 -*-
"""pneumonia_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5YomBYlZ0IMaUxnDCwJmNgVC_O1Jrok
"""

print('Ali Ahmed')

import tensorflow as tf
import tensorflow_datasets as tfds

(ds_train, ds_test), ds_info = tfds.load('pneumonia_mnist', split=['train[:80%]', 'train[80%:]'], as_supervised=True, with_info=True)

IMG_SIZE = 128

def preprocess(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

train_ds = ds_train.map(preprocess).shuffle(1000).batch(32)
val_ds   = ds_test.map(preprocess).batch(32)

for image, label in train_ds.take(1):
    print(f"Image batch shape: {image.shape}")
    print(f"Label batch: {label[:10].numpy()}")

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(IMG_SIZE, IMG_SIZE, 1)),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(train_ds, epochs=25, validation_data=val_ds, callbacks=[early_stop])

test_loss, test_acc = model.evaluate(val_ds)
print(f"\n✅ Test Accuracy: {test_acc * 100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

model.save("pneumonia_model.h5")
print("Model saved successfully as cnn_corvit.h5")

from google.colab import files
files.download('pneumonia_model.h5')

